version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: textile_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: textile_inventory
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - textile_net

volumes:
  pg_data:

networks:
  textile_net:
