apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cnpg-db-user
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.postgres.username | b64enc | quote }}
  password: {{ .Values.postgres.password | b64enc | quote }}
