apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-cnpg-cluster
  namespace: {{ .Release.Namespace }}
spec:
  instances: 1

  storage:
    size: {{ .Values.postgres.storage | default "1Gi" }}

  bootstrap:
    initdb:
      database: {{ .Values.postgres.database }}
      owner: {{ .Values.postgres.username }}
      secret:
        name: {{ .Release.Name }}-cnpg-db-user
