apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: textile-inventory-management-backend:latest
          imagePullPolicy: Never  # Prevents Kubernetes from trying to pull the image
          ports:
            - containerPort: 3002
          volumeMounts:
            - mountPath: "/app/backend/database/sqllite"  
              name: sqlite-storage
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: sqlite-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: textile-inventory-management-frontend:latest
          imagePullPolicy: Never  # Prevents Kubernetes from trying to pull the image
          ports:
            - containerPort: 3000

