# app/models.py
from typing import Optional, List
from sqlmodel import Field, SQLModel, Relationship
from enum import Enum
from datetime import datetime


class Order(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    order_id: str = Field(index=True, unique=True)  # Autogenerated unique order ID
    number_of_overall_pieces: int
    types: str  # Saves it as string, you can save as JSON too
    colors: str  # Saves it as string, you can save as JSON too
    design_specs: Optional[str] = None
    customer_id: str  # Changed to text
    order_date: datetime
    start_date: datetime
    due_date: datetime
    special_notes: Optional[str] = None
    tasks: List["Task"] = Relationship(back_populates="order")
    size_chart: Optional[str] = Field(default=None)  # JSON string for size chart


class OrderCreate(SQLModel):
    number_of_overall_pieces: int
    types: str
    colors: str
    design_specs: Optional[str] = None
    customer_id: str
    order_date: datetime
    start_date: datetime
    due_date: datetime
    special_notes: Optional[str] = None


class OrderUpdate(SQLModel):
    number_of_overall_pieces: Optional[int] = None
    types: Optional[str] = None
    colors: Optional[str] = None
    design_specs: Optional[str] = None
    customer_id: Optional[str] = None
    order_date: Optional[datetime] = None
    start_date: Optional[datetime] = None
    due_date: Optional[datetime] = None
    special_notes: Optional[str] = None
    size_chart: Optional[str] = Field(default=None)


class TaskStatus(str, Enum):  # Use Enum for status
    NOT_STARTED = "Not Started"
    IN_PROGRESS = "In Progress"
    COMPLETED = "BLOCKED"


class Task(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    order_id: int = Field(foreign_key="order.id")
    order: Order = Relationship(back_populates="tasks")
    task_template_id: int = Field(foreign_key="tasktemplate.id")
    task_template: "TaskTemplate" = Relationship(back_populates="tasks")
    status: TaskStatus = Field(default=TaskStatus.NOT_STARTED)  # Use the enum
    assigned_to: Optional[str] = None  # Who is in charge of the task?
    priority: Optional[str] = None  # High, medium, low
    due_date: datetime
    notes: Optional[str] = None
    order_position: int  # Order of the task for the order


class TaskCreate(SQLModel):
    order_id: int
    task_template_id: int
    status: TaskStatus = Field(default=TaskStatus.NOT_STARTED)
    assigned_to: Optional[str] = None
    priority: Optional[str] = None
    due_date: datetime
    notes: Optional[str] = None
    order_position: int


class TaskUpdate(SQLModel):
    status: Optional[TaskStatus] = None
    assigned_to: Optional[str] = None
    priority: Optional[str] = None
    due_date: Optional[datetime] = None
    notes: Optional[str] = None
    order_position: Optional[int] = None


class TaskTemplate(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str  # e.g., "Cutting", "Weaving", "Printing"
    description: Optional[str] = None
    order_position: int  # The template order position
    tasks: List["Task"] = Relationship(
        back_populates="task_template"
    )  # Connect to tasks


class TaskTemplateCreate(SQLModel):
    name: str
    description: Optional[str] = None
    order_position: int


class TaskTemplateUpdate(SQLModel):
    name: Optional[str] = None
    description: Optional[str] = None
    order_position: Optional[int] = None
