export const PurchaseOrderUnit = {
    PROCUREMENT: "PROCUREMENT",
    CUTTING: "CUTTING",
    COLLAR: "COLLAR",
    PRINTING: "PRINTING",
    EMBROIDERY: "EMBROIDERY",
    STITCHING: "STITCHING",
    PACKAGING: "PACKAGING",
    UNASSIGNED: "UNASSIGNED",
};